### ISSUE TITLE
iOS platform target is higher than react-native default

### ISSUE THREAD

**Issue by sattaman** [adobe/react-native-acpanalytics#37]
Is targetting ios 10 required? An out the box react-native installation currently targets 9, which then means adding this library leads to the following error: 

```
[!] CocoaPods could not find compatible versions for pod "RCTACPAnalytics":
  In Podfile:
    RCTACPAnalytics (from `../node_modules/@adobe/react-native-acpanalytics`)

Specs satisfying the `RCTACPAnalytics (from `../node_modules/@adobe/react-native-acpanalytics`)` dependency were found, but they required a higher minimum deployment target.

```
Updating your library to target 9 seems to work although not tested fully, is there a reason you have targetted 10?

**Comment by nporter-adbe** [comment]
Yes iOS 10.0 is required. 
https://aep-sdks.gitbook.io/docs/resources/frequently-asked-questions#what-os-versions-are-supported

**Comment by sattaman** [comment]
Nice response times 👏 

Probably worth adding to docs? I'll close this anyhow and look into whether we can update.

**Comment by nporter-adbe** [comment]
Added a note in the trouble shooting section: https://github.com/adobe/react-native-acpcore#trouble-shooting
