### ISSUE TITLE
Verbose logging?

### ISSUE THREAD

**Issue by danielimmke** [adobe/react-native-acpanalytics#42]
How verbose is verbose logging? I think I have this framework setup but I don't get any logging when I run the app. I have a trackState call and it doesn't tell me if it actually executes it or not.

I've as closely adapted this package and the SDKs for Android and iOS as I can, looking at code examples and everything compiles and I am able to log out information but how can I actually know if it's working?

**Comment by nporter-adbe** [comment]
Hi @danielimmke, verbose logging should log pretty much everything that is happening within the SDK. After running the app you should see logs in Android Studio/Xcode indicating that the SDK has booted up and additional logs when APIs are invoked.

Here is as sample of some of the logs I see on bootup in Xcode when I run the sample app in the sample directory:
```
2020-05-14 12:54:39.511137-0600 ACPAnalyticsSample[98367:3051857] [AdobeExperienceSDK TRACE <EventHub(AMSEventHub)>]: Processing Event #0 - {
    class: "Event",
    name: "EventHub",
    uniqueIdentifier: "2E44E3D7-F468-4FC0-A760-E0E5DCA8FB78",
    source: "com.adobe.eventSource.booted",
    type: "com.adobe.eventType.hub",
    pair_id: "",
    response_pair_id: "4",
    event_number: 0,
    timestamp: "1589482479510 ms",
    data: 
}
2020-05-14 12:54:39.511796-0600 ACPAnalyticsSample[98367:3051857] [AdobeExperienceSDK TRACE <EventHub(AMSEventHub)>]: Event #0 (com.adobe.eventType.hub) resulted in 0 consequence events.  Time in rules was 0 milliseconds.
```

**Comment by danielimmke** [comment]
Ah okay - That was the misunderstanding. I was assuming it would be logging things with the rest of the react native logging but since I'm starting it inside native code that makes sense. Thanks.
