### ISSUE TITLE
[ACPMobileServices trackAdobeDeepLink:url]

### ISSUE THREAD

**Issue by stereodenis** [adobe/react-native-acpanalytics#57]
https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics-mobile-services/mobileservices-api-reference
`[ACPMobileServices trackAdobeDeepLink:url]`
Can't find how to track deeplinks in React Native

### Expected Behaviour
There is ACPMobileServices implementation for iOS

### Actual Behaviour
There is no ACPMobileServices implementation for iOS

#### Platform and Version
React Native

**Comment by nporter-adbe** [comment]
Hi @stereodenis 👋🏻 

We currently have no plans to provide official support to ACPMobileServices through a React Native wrapper. In the case that you'd like to track a deep link inside of a React Native app, you have a few options:

1. Use a 3rd party wrapper: https://github.com/Foursum/react-native-acpmobileservices As a disclaimer, we have not tested this package, and Adobe does not officially support this package, so use at your own risk. We have an active community of developers who use our products, so you may find a way to leverage their work to fit your needs.
2. Include the Mobile Services libraries manually.  You can visit: https://github.com/Adobe-Marketing-Cloud/acp-sdks/ and find steps to include the .XCFramework and .aar file for iOS and Android, respectively. Then you can use the Mobile Services APIs in your native code
3. Build your own wrapper for Mobile Services. You can use this repo as an example of how we create our wrappers.

**Comment by stereodenis** [comment]
@nporter-adbe I made own wrapper and we merge it here https://github.com/Foursum/react-native-acpmobileservices. Now it works like another adobe RN wrappers.

Do you have any plans to move it to Adobe github organization?

**Comment by nporter-adbe** [comment]
Glad to hear you were able to get it working. 

We won't be able to move that project under the Adobe org. Projects under the Adobe org are projects that are written and maintained by Adobe employees.
