### ISSUE TITLE
Android release bundle fails at :app:mergeReleaseAssets

### ISSUE THREAD

**Issue by gingerbenw** [adobe/react-native-acpanalytics#67]
### Expected Behaviour
Android release bundle is successful

### Actual Behaviour
Build fails at step :app:mergeReleaseAssets - this worked a month ago, and none of the app dependencies have changed.

#### Platform and Version
```
    "react-native": "0.64.1",
    "@adobe/react-native-acpanalytics": "^1.1.6",
    "@adobe/react-native-acpcore": "^1.2.5",
    "@adobe/react-native-acpuserprofile": "^1.1.0"
```

#### Logs taken while reproducing problem
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseAssets'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :app > com.adobe.marketing.mobile:analytics:1.2.7
```

**Comment by gingerbenw** [comment]
Apologies for the lack of reproducible code, I'm not really sure what would be valid to include...

**Comment by rymorale** [comment]
Hi @gingerbenw, there was an issue present in the android analytics 1.2.7 release which was resolved in the android analytics 1.2.8 release. There have been issues with fetching the latest 1.2.8 release from maven though. Can you try updating your maven repository and android analytics version as described in https://experienceleaguecommunities.adobe.com/t5/adobe-experience-platform-sdks/how-to-i-update-sdk-to-android-analytics-1-2-8/m-p/417203/highlight/true#M242? Hopefully this resolves your issue.

**Comment by gingerbenw** [comment]
Hi @rymorale, thanks for the quick response, that appears to have done the trick, thankyou!

For clarity: I added `mavenCentral()` to the repositories list at the bottom of `android/build.gradle`

**Comment by rymorale** [comment]
Thanks for the update. Closed this issue as it has been resolved.
