### ISSUE TITLE
Move from jcenter to maven

### ISSUE THREAD

**Issue by kkkorez** [adobe/react-native-acpanalytics#68]
Is there any plan to remove usages of jcenter() repository from your build scripts and migrate your build to other maven repositories?

**Comment by cacheung** [comment]
Thank you for the inquiry. There were some components using jcenter() previously, so we kept it there.  we plan to review this soon.

Calise Cheung
Mobile Engineer

**Comment by cacheung** [comment]
This is implemented in release 2.0.1.
