### ISSUE TITLE
Does Adobe provide Crash Analytics for the mobile app developed using React Native / Native Code

### ISSUE THREAD

**Issue by samir-mirani-tcs** [adobe/react-native-acpanalytics#72]
Hi there!

Just wanted to know whether Adobe provide Crash Analytics for the mobile app developed using React Native / Native Code or not?

**Comment by caseymcj** [comment]
Hi @samir-mirani-tcs, It looks like this may be a duplicate of [react-native-acpcore #132](https://github.com/adobe/react-native-acpcore/issues/132). Please let us know if you have any further questions over in that issue. I'll move ahead and close this issue for now. Thanks for your questions and interest.
