### ISSUE TITLE
No such file - react-native-acpanalytics-main/adobe-react-native-acpanalytics-2.0.1.tgz

### ISSUE THREAD

**Issue by ashwanihundwani1986** [adobe/react-native-acpanalytics#75]
Getting Error while running the react native sample app:

npm WARN tarball tarball data for @adobe/react-native-acpanalytics@file:/Users/ashwanihundwani/Desktop/Adobe/react-native-acpanalytics-main/adobe-react-native-acpanalytics-2.0.1.tgz (sha512-yEyoXps7nO+hss/NeYAdlw+ZJixEYjAEF8Dn/3pQUo5rg5etb3tTlnzj09AlKL9kt52c8rwgITAELyityHD1Bw==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @adobe/react-native-acpanalytics@file:/Users/ashwanihundwani/Desktop/Adobe/react-native-acpanalytics-main/adobe-react-native-acpanalytics-2.0.1.tgz (sha512-yEyoXps7nO+hss/NeYAdlw+ZJixEYjAEF8Dn/3pQUo5rg5etb3tTlnzj09AlKL9kt52c8rwgITAELyityHD1Bw==) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/ashwanihundwani/Desktop/Adobe/react-native-acpanalytics-main/adobe-react-native-acpanalytics-2.0.1.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/ashwanihundwani/Desktop/Adobe/react-native-acpanalytics-main/adobe-react-native-acpanalytics-2.0.1.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ashwanihundwani/.npm/_logs/2022-09-30T06_01_17_033Z-debug-0.log

**Comment by cacheung** [comment]
@ashwanihundwani1986 
The sample app was setup to build with the ACPAnalytics source code, so it was setup with "adobe-react-native-acpanalytics-2.0.1.tgz" in 
https://github.com/adobe/react-native-acpanalytics/blob/main/sample/ACPAnalyticsSampleApp/package.json#L16

To run with Sample app, you can change the above line in package.json to 
 "@adobe/react-native-acpanalytics": ">=2.0.0",
then npm install.
(The sample app will run with the latest react-native-acpanalytics from npm)
 
 Or if you want to run with current setup with source,
 You can
 `cd ACPAnalyticsSampleApp`
 `make sync`
 (we have a make file to build  the adobe-react-native-acpanalytics-2.0.1.tgz)
 
 Then it should find the missing tgz file.
 
 Thanks,
 Calise

**Comment by spoorthipujariadobe** [comment]
@ashwanihundwani1986 did the solution provided fix your issue? If yes, please close this issue.
