### ISSUE TITLE
Error upgrading to version 2.0.0 from ^1.2.6 for M1

### ISSUE THREAD

**Issue by ShalviKubal** [adobe/react-native-acpanalytics#76]
I am facing following issue while upgrading the package to on Mac M1
```
LoadError - dlopen(/Users/*///vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '////*/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

   report.issues = results['items'].map { |item| Issue.new(item) }
                   ^^^^
```
Things to note
1. https://github.com/adobe/react-native-acpanalytics/releasesonly allows installing ACPAnalytics via Cocoapods

Things I tried 
1. I tried to upgrade it but it fails due to system architecture -> The flutter bundle is for x86_64 and m1 is arm64e
2. I tried various things like reinstalling the ruby version via rosetta which is like a translator to convert instructions designed for the intel chip into the one suited for the m1 chip.
3. Played around with various versions
5. Tried all solutions from https://stackoverflow.com/questions/11677771/rvm-command-not-found-mac-ox

I think this is more to do with Mac M1 chip because when I tried to upgrade react-native-acpanalytics on my older Mac with an intel chip, it was a success. It would be great if I can get any help here.

**Comment by cacheung** [comment]
Hi @ShalviKubal, may I know which step you were getting the error?  Were you able to run pod install successfully, or the error shows before that?  Or you get the error while running the app?

How do you upgrade the react-native-acpanalytics package?  

Best Regards,
Calise

**Comment by ShalviKubal** [comment]
Hi @cacheung thanks for the follow-up. I upgraded the package in `package.json` and run `yarn install`. I get the error when I run `yarn install` on my Mac with an M1 chip. I don't get the error for running on my Mac with an intel chip though. Since I get the error during installation only I cannot build my app.

**Comment by cacheung** [comment]
What is your Ruby version when do ruby --version?
Can you remove the acp packages in the package.json and run yarn install, are you seeing the same error?  Just want to rule out if it is ACP packages related.   
I am using npm install for our test file, and I don't see the Ruby error on M1.
I have Ruby version 2.6.8.

**Comment by ShalviKubal** [comment]
Ruby version: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`
No error is seen if the acp package is removed altogether. Also, no error is seen with `react-native-acpanalytics` version `^1.2.6`. The error starts to pop only if I try to upgrade the version to >= 2.0.0

**Comment by cacheung** [comment]
Thanks for the info.  We need some time to investigate, will come back.

**Comment by cacheung** [comment]
@ShalviKubal I did some search online and saw some posts had similar errors on M1 which is Cocoapods related.

https://github.com/CocoaPods/CocoaPods/issues/11258

https://stackoverflow.com/questions/67443265/error-regarding-undefined-method-map-for-nilnilclass-for-flutter-app-cocoap

https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1

I suspect this is related the setup on running Cocoapod on your M1 machine.  Do Cocoapods work for other projects on this M1 machine?

**Comment by cacheung** [comment]
@ShalviKubal Have you confirmed the Cocoapod works properly on your M1 machine?  Have you got the package to work with your app?

**Comment by ShalviKubal** [comment]
@cacheung unfortunately I didn't get a chance to look into it. But I will take a look at this somewhere this month. Thanks for following up on this.

**Comment by cacheung** [comment]
I am closing this ticket for now.  We can open a new one if we need follow up.
