### ISSUE TITLE
[customer question] How to implement adobe analytics on expo managed project

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/react-native-acpanalytics#78]
```
Is it possible to integrate adobe analytics in the mobile app which is built using react native expo managed project.
Expo's config plugins help changing native code, but there is no guidance how to create config plugin and implement analytics on expo managed project.
```
This issue was originally asked on https://github.com/AdobeDocs/aep-mobile-sdkdocs/issues/289. Since it's a question related to this ACP analytics wrapper, I moved it here to better manage the customer issue.

**Comment by emdobrin** [comment]
Hi @MarKamenov, 

Thank you for your question. While we are always exploring new technologies and evaluating their potential impact on the AEP Mobile SDKs, we do not currently have plans to add support for Expo. This decision was made after careful consideration of a variety of factors, including the needs of our current customer base, the resources required for implementation, and the potential impact on our product roadmap.

However, we are constantly listening to our customers' feedback and suggestions, and we take them into account when making decisions about future product development. We will continue to monitor the development of Expo and assess its potential impact on the Adobe Experience Platform Data Collection SDKs.

Thanks,
Emilia
